github: [hamzanachite]
patreon:
open_collective: nmapvuejs
ko_fi: J3J61HQIT1
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar: hamzanachite
buy_me_a_coffee:
thanks_dev: gh/hamzanachite
custom:
  - 'https://ko-fi.com/J3J61HQIT1'
